version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: ajv
    versions:
    - 7.1.1
    - 7.2.1
    - 7.2.3
    - 8.0.1
    - 8.0.3
    - 8.0.5
    - 8.1.0
  - dependency-name: eslint-config-kentcdodds
    versions:
    - 17.3.2
    - 17.4.1
    - 17.5.0
    - 17.6.0
    - 17.7.0
  - dependency-name: husky
    versions:
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: acorn
    versions:
    - 8.0.5
    - 8.1.0
    - 8.1.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.8
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: '@rollup/plugin-commonjs'
    versions:
    - 28.0.1
  - dependency-name: '@rollup/plugin-json'
    versions:
    - 6.1.0
  - dependency-name: '@rollup/plugin-node-resolve'
    versions:
    - 15.3.0
  - dependency-name: rollup
    versions:
    - 4.28.0
  - dependency-name: rollup-plugin-auto-external
    versions:
      - 2.0.0
  - dependency-name: memfs
    versions:
    - 4.14.1
  - dependency-name: vue-eslint-parser
    versions:
    - 7.4.1
    - 7.5.0
    - 7.6.0
  - dependency-name: vite
    versions:
    - 6.0.3
  - dependency-name: vitest
    versions:
    - 2.1.8
  - dependency-name: '@vitest/coverage-v8'
    versions:
    - 2.1.8
  - dependency-name: '@vitest/ui'
    versions:
    - 2.1.8
  - dependency-name: pretty-format
    versions:
    - 26.6.2
